#!/usr/bin/env python3
import rospy
from custom_msg_util import CustomMsgUtil

if __name__ == '__main__':
    node_name = 'custom_msg_node'
    rospy.init_node(node_name, anonymous=True)
    node = CustomMsgUtil()
    print(node_name + " setup")
    while not rospy.is_shutdown():
        rospy.spin()

