#!/usr/bin/env python3

import rospy
from mission_planner import MissionPlanner

if __name__ == '__main__':
    node_name = 'mission_planner_node'
    rospy.init_node(node_name, anonymous=True)
    node = MissionPlanner()
    print(node_name + " setup")
    while not rospy.is_shutdown():
        rospy.spin()
