obstacle_range: 6.0
raytrace_range: 7.0
#footprint: [[x0, y0], [x1, y1], ... [xn, yn]]
robot_radius: 0.2
inflation_radius: 0.55

observation_sources: laser_scan_sensor #odom_sensor

laser_scan_sensor: {sensor_frame: laser, data_type: LaserScan, topic: /scan, marking: true, clearing: true}
#odom_sensor: {sensor_frame: frame_name, data_type: Odometry, topic: /mobile_base_controller/odom, marking: true, clearing: true}

