global_costmap:
  global_frame: map
  robot_base_frame: base_link
  update_frequency: 5.0
  publish_frequency: 2.0
  static_map: true
  resolution: 0.05
  transform_tolerance: 0.5
  obstacle_range: 6.0
  raytrace_range: 7.0
  robot_radius: 0.2
  inflation_radius: 0.55
  observation_sources: laser_scan_sensor
  laser_scan_sensor: {sensor_frame: laser, data_type: LaserScan, topic: /scan, marking: true, clearing: true}
