local_costmap:
  global_frame: odom
  robot_base_frame: base_link
  update_frequency: 1.0
  publish_frequency: 2.0
  transform_tolerance: 0.2
  resolution: 0.05
  static_map: false
  rolling_window: true
  width: 10.0
  height: 10.0